sudo: required
language: go
go:
  - tip
before_install:
  - pip install --user awscli
  - pip install --user aws-sam-cli
install:
  - go get -t ./...
deploy:
  # dev
  - provider: script
    script: make deploy
    skip_cleanup: true
    on:
      branch: master
  # demo
  - provider: script
    script: AWS_ACCESS_KEY_ID=$AWS_915001051872_ID AWS_SECRET_ACCESS_KEY=$AWS_915001051872_SECRET make demo
    skip_cleanup: true
    on:
      branch: master
  # production
  - provider: script
    script: AWS_ACCESS_KEY_ID=$AWS_192458993663_ID AWS_SECRET_ACCESS_KEY=$AWS_192458993663_SECRET make prod
    skip_cleanup: true
    on:
      branch: master

env:
  - GO111MODULE=on
