sudo: required
language: go
go:
  - tip
before_install:
  - pyenv global 3.6.7
  - pip install --user awscli
  - pip install --user aws-sam-cli
install:
  - go get -t ./...
deploy:
  # dev
  - provider: script
  #TODO Explore if we can replace installation ID stage uneet-dev with variable 
    script: aws configure set profile.ins-dev.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV &&
        aws configure set profile.ins-dev.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV &&
        aws configure set profile.ins-dev.region $AWS_DEFAULT_REGION &&
        aws configure --profile ins-dev list &&
        make deploy
    skip_cleanup: true
    on:
      branch: master
  # demo
  - provider: script
    script: aws configure set profile.ins-demo.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEMO && aws configure set profile.ins-demo.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEMO && aws configure set profile.ins-demo.region $AWS_DEFAULT_REGION && aws configure --profile ins-demo list && make demo
    skip_cleanup: true
    on:
      branch: master
  # production
  - provider: script
    script: aws configure set profile.ins-prod.aws_access_key_id $AWS_ACCOUNT_USER_ID_PROD && aws configure set profile.ins-prod.aws_secret_access_key $AWS_ACCOUNT_SECRET_PROD && aws configure set profile.ins-prod.region $AWS_DEFAULT_REGION && aws configure --profile ins-prod list && make prod
    skip_cleanup: true
    on:
      branch: master

env:
  - GO111MODULE=on
