#Variables for this script are stored on Travis
#Variables need for this script:
#For dev environment:
  # - AWS_PROFILE_DEV
  # - AWS_ACCOUNT_USER_ID_DEV
  # - AWS_ACCOUNT_SECRET_DEV
  # - AWS_DEFAULT_REGION
#For Demo environment:
  # - AWS_PROFILE_DEMO
  # - AWS_ACCOUNT_USER_ID_DEMO
  # - AWS_ACCOUNT_SECRET_DEMO
  # - AWS_DEFAULT_REGION
#For Prod environment:
  # - AWS_PROFILE_PROD
  # - AWS_ACCOUNT_USER_ID_PROD
  # - AWS_ACCOUNT_SECRET_PROD
  # - AWS_DEFAULT_REGION

language: go

before_install:
  - pyenv global 3.6.7
  - pip install --user awscli
  - pip install --user aws-sam-cli

install:
  - go get -t ./...

deploy:
  # Add a deploy stage for dev
  - provider: script
    script: TRAVIS_PROFILE=$AWS_PROFILE_DEV && aws configure set profile.$AWS_PROFILE_DEV.aws_access_key_id $AWS_ACCOUNT_USER_ID_DEV && aws configure set profile.$AWS_PROFILE_DEV.aws_secret_access_key $AWS_ACCOUNT_SECRET_DEV && aws configure set profile.$AWS_PROFILE_DEV.region $AWS_DEFAULT_REGION && aws configure --profile $AWS_PROFILE_DEV list && make deploy
    edge: true
    on:
      branch: master
  # Add a deploy stage for Prod
  - provider: script
    script: TRAVIS_PROFILE=$AWS_PROFILE_PROD && aws configure set profile.$AWS_PROFILE_PROD.aws_access_key_id $AWS_ACCOUNT_USER_ID_PROD && aws configure set profile.$AWS_PROFILE_PROD.aws_secret_access_key $AWS_ACCOUNT_SECRET_PROD && aws configure set profile.$AWS_PROFILE_PROD.region $AWS_DEFAULT_REGION && aws configure --profile $AWS_PROFILE_PROD list && make deploy
    edge: true
    on:
      branch: master
      tags: true

env:
  - GO111MODULE=on
